version: '3.8'

services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - 5341:80
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINUSERNAME: "t-raider-user"
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: "${seq_password_hash}"
      SEQ_FIRSTRUN_REQUIREAUTHENTICATIONFORHTTPINGESTION: "True"
    volumes:
      - seq-data:/data
    restart: unless-stopped

  seq-cli:
    image: datalust/seqcli:latest
    container_name: seq-cli
    command: apikey create -t t-raider-apikey --token ${seq_apikey} -s http://seq --connect-username t-raider-user --connect-password ${seq_password}
    depends_on:
      seq:
        condition: service_started
    restart: on-failure:10

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: t-raider-database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "${postgres_password}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d t-raider-database"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/data
      ALLOW_PLAINTEXT_LISTENER: yes
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions.sh", "--bootstrap-server", "PLAINTEXT://127.0.0.1:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    restart: unless-stopped

  migrator:
    image: cr.yandex/crpms6iaa8rs3mvdhl1a/t_raider_migrator:latest
    container_name: migrator
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__TRaiderDatabase: "User ID=admin;Password=${postgres_password};Host=postgres;Port=5432;Database=t-raider-database;"
    restart: on-failure

  worker:
    image: cr.yandex/crpms6iaa8rs3mvdhl1a/t_raider_worker:latest
    container_name: worker
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      Kafka__BootstrapServers: "kafka:9092"
      ConnectionStrings__TRaiderDatabase: "User ID=admin;Password=${postgres_password};Host=postgres;Port=5432;Database=t-raider-database;"
      Gpt__Uri: "https://api.proxyapi.ru/openai/v1"
      Gpt__ApiKey: "${gpt_api_key}"
    restart: on-failure

  services:
    image: cr.yandex/crpms6iaa8rs3mvdhl1a/t_raider_services:latest
    container_name: services
    ports:
      - 4000:8080
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      Kafka__BootstrapServers: "kafka:9092"
      ConnectionStrings__TRaiderDatabase: "User ID=admin;Password=${postgres_password};Host=postgres;Port=5432;Database=t-raider-database;"
      Gpt__Uri: "https://api.proxyapi.ru/openai/v1"
      Gpt__ApiKey: "${gpt_api_key}"
    restart: on-failure

  # telegram-bot:
  #   build:
  #     context: ./bot
  #     dockerfile: Dockerfile
  #   container_name: telegram-bot
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     kafka:
  #       condition: service_healthy
  #   environment:
  #     BOT_TOKEN: your_bot_token_here
  #     WEBHOOK_URL: https://your-domain.com
      
  #     PORT: 3000
  #     NODE_ENV: development
      
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #     DB_NAME: t-raider-database
  #     DB_USER: admin
  #     DB_PASSWORD: password
      
  #     KAFKA_BROKERS: kafka:9092
  #     KAFKA_CLIENT_ID: telegram-bot
      
  #     LOG_LEVEL: info
  #   volumes:
  #     - ./bot/logs:/app/logs
  #   restart: unless-stopped
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 512M

volumes:
  seq-data:
  postgres_data:
